import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import textToHTML from "../logic/text2html";
import { useState } from "react";
import outputHTML from "../logic/output";

export default function Home() {
  const [inp, setInp] = useState("");

  const [out, setOut] = useState([]);

 

 


  const inputData = async (e) => {
    await setInp(e.split("\n"));
    setOut(newText)


    const output = textToHTML(inp);
    console.log("output is ", output);
  let newText = []
    for (let i = 0; i < output.length; i++) {
     
     let t = outputHTML(output[i])
     t= t.replace(/'/g, 'A')
     newText.push(t)
     console.log("New text is ", newText)
    
    }
    let j="";
    for(let i=0; i<newText.length; i++){
      j=j+newText[i]
      document.getElementById("demo").innerHTML=j
    }
    newText=[]
    };
const cleanText= ()=>{
  setInp("")
  document.getElementById("demo").innerHTM = ""
}
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div><button onClick={cleanText}>Clean</button></div>
      <div
        style={{ display: "flex", flextDirection: "column", height: "500px" }}
      >
        <div>
       
          <textarea
            type="textarea"
            style={{ width: "500px", height: "100%" , fontSize:"14px"}}
            onChange={(e) => inputData(e.target.value)}
          />
        </div>
       
        <div
          style={{
            margin:"",
            width: "500px",
            height: "auto",
            backgroundColor: "white",
            overflow:"scroll", 
            border:"1px solid lightgray",

          }}
        >

        <div id="demo" style={{margin:"20px"}}></div>

       
    
        </div>
      </div>
    </div>
  );
}
